export const customerHistoryButton = '[ng-class="btnClass3"]';
export const tdFirstName1 = "tbody > :nth-child(1) > :nth-child(1)";
export const searchField = ".form-control";
export const searchResult = "tr.ng-scope > :nth-child(1)";
export const searchResultEmpty = ".table";
export const deleteButton = ":nth-child(1) > :nth-child(5) > button";
export const firstNameFilter = ":nth-child(1) > a";
export const lastNameFilter = ":nth-child(2) > a";
export const postCodeFilter = ":nth-child(3) > a";
export const resultFirstNameFilter = "tbody > :nth-child(1) > :nth-child(1)";
export const resultLastNameFilter = "tbody > :nth-child(1) > :nth-child(2)";
export const resultPostCodeFilter = "tbody > :nth-child(1) > :nth-child(3)";
