export const customerLogin = ".borderM > :nth-child(1) > .btn";
export const selectField = "#userSelect";
export const loginButton = "form.ng-valid > .btn";
export const successLogin = ".borderM > :nth-child(1) > strong";
export const logoutButton = ".logout";
export const customerNameLabel = "label";
export const homeButton = ".home";
export const infoAccount = ".borderM > :nth-child(3)";
export const bankManagerLogin = ".borderM > :nth-child(3) > .btn";
